version: '2'

services:

  elasticsearch:
    build:
      context: heartbeat/
    volumes:
      - ./heartbeat/config/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:rw

    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    
    networks:
      - heartbeat


networks:

  heartbeat:
    driver: bridge
